---
- name: Prepare
  hosts: all
  tasks:
    - name: copy raspberry-pi os default config.txt
      copy:
        src: files/config.txt
        dest: /boot/config.txt
        owner: root
        group: root
        mode: "0755"

    - name: copy raspberry-pi os default rc.local
      copy:
        src: files/rc.local
        dest: /etc/rc.local
        owner: root
        group: root
        mode: "0755"
